language: java
jdk: openjdk9
script:
- "./mvnw test"
notifications:
  slack:
    rooms:
      secure: $secure_token
    on_success: always
    on_failure: always
    template:
    - "%{repository_slug} (%{commit}) : %{message}"
    - 'Build details: %{build_url}'
